# Generated by Django 2.0.13 on 2019-05-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('Present_address', models.TextField(max_length=400)),
                ('Permanent_address', models.TextField(max_length=400)),
                ('contact', models.CharField(max_length=11)),
                ('avg_cgpa', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
